//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.42.
// 
namespace bitirmePDA_WM5.hataWebServisi {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="hataWSSoap", Namespace="http://localhost/hataWS/")]
    public partial class hataWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public hataWS() {
            this.Url = "http://160.75.96.32/1/webServices/hataWS.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/hataWS/getir", RequestNamespace="http://localhost/hataWS/", ResponseNamespace="http://localhost/hataWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public hataBilgi[] getir(string projeIsmi) {
            object[] results = this.Invoke("getir", new object[] {
                        projeIsmi});
            return ((hataBilgi[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begingetir(string projeIsmi, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getir", new object[] {
                        projeIsmi}, callback, asyncState);
        }
        
        /// <remarks/>
        public hataBilgi[] Endgetir(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((hataBilgi[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/hataWS/ilkSoru", RequestNamespace="http://localhost/hataWS/", ResponseNamespace="http://localhost/hataWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public soruBilgi ilkSoru(string projeIsmi) {
            object[] results = this.Invoke("ilkSoru", new object[] {
                        projeIsmi});
            return ((soruBilgi)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginilkSoru(string projeIsmi, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ilkSoru", new object[] {
                        projeIsmi}, callback, asyncState);
        }
        
        /// <remarks/>
        public soruBilgi EndilkSoru(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((soruBilgi)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/hataWS/sonraki", RequestNamespace="http://localhost/hataWS/", ResponseNamespace="http://localhost/hataWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public soruBilgi sonraki(uint id) {
            object[] results = this.Invoke("sonraki", new object[] {
                        id});
            return ((soruBilgi)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginsonraki(uint id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sonraki", new object[] {
                        id}, callback, asyncState);
        }
        
        /// <remarks/>
        public soruBilgi Endsonraki(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((soruBilgi)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/hataWS/gonder", RequestNamespace="http://localhost/hataWS/", ResponseNamespace="http://localhost/hataWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string gonder(string projeIsmi, uint sonSoruId, int cevap, string hataAciklama, uint yollayanId) {
            object[] results = this.Invoke("gonder", new object[] {
                        projeIsmi,
                        sonSoruId,
                        cevap,
                        hataAciklama,
                        yollayanId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begingonder(string projeIsmi, uint sonSoruId, int cevap, string hataAciklama, uint yollayanId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("gonder", new object[] {
                        projeIsmi,
                        sonSoruId,
                        cevap,
                        hataAciklama,
                        yollayanId}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endgonder(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/hataWS/")]
    public partial class hataBilgi {
        
        private string projeIsmiField;
        
        private string aciklamaField;
        
        private string zamanField;
        
        /// <remarks/>
        public string projeIsmi {
            get {
                return this.projeIsmiField;
            }
            set {
                this.projeIsmiField = value;
            }
        }
        
        /// <remarks/>
        public string aciklama {
            get {
                return this.aciklamaField;
            }
            set {
                this.aciklamaField = value;
            }
        }
        
        /// <remarks/>
        public string zaman {
            get {
                return this.zamanField;
            }
            set {
                this.zamanField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/hataWS/")]
    public partial class soruBilgi {
        
        private uint idField;
        
        private string soruField;
        
        private string kNotField;
        
        private uint evetIdField;
        
        private uint hayirIdField;
        
        /// <remarks/>
        public uint id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string soru {
            get {
                return this.soruField;
            }
            set {
                this.soruField = value;
            }
        }
        
        /// <remarks/>
        public string kNot {
            get {
                return this.kNotField;
            }
            set {
                this.kNotField = value;
            }
        }
        
        /// <remarks/>
        public uint evetId {
            get {
                return this.evetIdField;
            }
            set {
                this.evetIdField = value;
            }
        }
        
        /// <remarks/>
        public uint hayirId {
            get {
                return this.hayirIdField;
            }
            set {
                this.hayirIdField = value;
            }
        }
    }
}
