//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.42.
// 
namespace bitirmePDA_WM5.projeWebServisi {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="projeWSSoap", Namespace="http://localhost/projeWS/")]
    public partial class projeWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public projeWS() {
            this.Url = "http://160.75.96.32/1/webServices/projeWS.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/projeWS/projeleriListele", RequestNamespace="http://localhost/projeWS/", ResponseNamespace="http://localhost/projeWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] projeleriListele() {
            object[] results = this.Invoke("projeleriListele", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginprojeleriListele(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("projeleriListele", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndprojeleriListele(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/projeWS/projeyeAitCozulmemisHataSayisi", RequestNamespace="http://localhost/projeWS/", ResponseNamespace="http://localhost/projeWS/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public uint projeyeAitCozulmemisHataSayisi(string projeIsmi) {
            object[] results = this.Invoke("projeyeAitCozulmemisHataSayisi", new object[] {
                        projeIsmi});
            return ((uint)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginprojeyeAitCozulmemisHataSayisi(string projeIsmi, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("projeyeAitCozulmemisHataSayisi", new object[] {
                        projeIsmi}, callback, asyncState);
        }
        
        /// <remarks/>
        public uint EndprojeyeAitCozulmemisHataSayisi(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((uint)(results[0]));
        }
    }
}
