// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package projeWS;


public class ProjeleriListeleResponse {
    protected projeWS.ArrayOfString projeleriListeleResult;
    
    public ProjeleriListeleResponse() {
    }
    
    public ProjeleriListeleResponse(projeWS.ArrayOfString projeleriListeleResult) {
        this.projeleriListeleResult = projeleriListeleResult;
    }
    
    public projeWS.ArrayOfString getProjeleriListeleResult() {
        return projeleriListeleResult;
    }
    
    public void setProjeleriListeleResult(projeWS.ArrayOfString projeleriListeleResult) {
        this.projeleriListeleResult = projeleriListeleResult;
    }
}
