// This class was generated by 172 StubGenerator.
// Contents subject to change without notice.
// @generated

package projeWS;

public interface ProjeWSSoap extends java.rmi.Remote {
	public projeWS.ArrayOfString projeleriListele() throws java.rmi.RemoteException;

	public long projeyeAitCozulmemisHataSayisi(java.lang.String projeIsmi) throws java.rmi.RemoteException;

}
