// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package kullaniciWS;


public class Giris {
    protected java.lang.String isim;
    protected java.lang.String sifre;
    
    public Giris() {
    }
    
    public Giris(java.lang.String isim, java.lang.String sifre) {
        this.isim = isim;
        this.sifre = sifre;
    }
    
    public java.lang.String getIsim() {
        return isim;
    }
    
    public void setIsim(java.lang.String isim) {
        this.isim = isim;
    }
    
    public java.lang.String getSifre() {
        return sifre;
    }
    
    public void setSifre(java.lang.String sifre) {
        this.sifre = sifre;
    }
}
