// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package kullaniciWS;


public class GirisResponse {
    protected boolean girisResult;
    
    public GirisResponse() {
    }
    
    public GirisResponse(boolean girisResult) {
        this.girisResult = girisResult;
    }
    
    public boolean isGirisResult() {
        return girisResult;
    }
    
    public void setGirisResult(boolean girisResult) {
        this.girisResult = girisResult;
    }
}
