// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package kullaniciWS;


public class IdGetirResponse {
    protected long idGetirResult;
    
    public IdGetirResponse() {
    }
    
    public IdGetirResponse(long idGetirResult) {
        this.idGetirResult = idGetirResult;
    }
    
    public long getIdGetirResult() {
        return idGetirResult;
    }
    
    public void setIdGetirResult(long idGetirResult) {
        this.idGetirResult = idGetirResult;
    }
}
