// This class was generated by 172 StubGenerator.
// Contents subject to change without notice.
// @generated

package kullaniciWS;

public interface KullaniciWSSoap extends java.rmi.Remote {
	public boolean giris(java.lang.String isim, java.lang.String sifre) throws java.rmi.RemoteException;

	public long idGetir(java.lang.String isim) throws java.rmi.RemoteException;

	public java.lang.String tipGetir(java.lang.String isim) throws java.rmi.RemoteException;

}
