// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package kullaniciWS;


public class TipGetir {
    protected java.lang.String isim;
    
    public TipGetir() {
    }
    
    public TipGetir(java.lang.String isim) {
        this.isim = isim;
    }
    
    public java.lang.String getIsim() {
        return isim;
    }
    
    public void setIsim(java.lang.String isim) {
        this.isim = isim;
    }
}
