// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package kullaniciWS;


public class TipGetirResponse {
    protected java.lang.String tipGetirResult;
    
    public TipGetirResponse() {
    }
    
    public TipGetirResponse(java.lang.String tipGetirResult) {
        this.tipGetirResult = tipGetirResult;
    }
    
    public java.lang.String getTipGetirResult() {
        return tipGetirResult;
    }
    
    public void setTipGetirResult(java.lang.String tipGetirResult) {
        this.tipGetirResult = tipGetirResult;
    }
}
