// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package hataWS;


public class ArrayOfHataBilgi {
    protected hataWS.HataBilgi[] hataBilgi;
    
    public ArrayOfHataBilgi() {
    }
    
    public ArrayOfHataBilgi(hataWS.HataBilgi[] hataBilgi) {
        this.hataBilgi = hataBilgi;
    }
    
    public hataWS.HataBilgi[] getHataBilgi() {
        return hataBilgi;
    }
    
    public void setHataBilgi(hataWS.HataBilgi[] hataBilgi) {
        this.hataBilgi = hataBilgi;
    }
}
