// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package hataWS;


public class GetirResponse {
    protected hataWS.ArrayOfHataBilgi getirResult;
    
    public GetirResponse() {
    }
    
    public GetirResponse(hataWS.ArrayOfHataBilgi getirResult) {
        this.getirResult = getirResult;
    }
    
    public hataWS.ArrayOfHataBilgi getGetirResult() {
        return getirResult;
    }
    
    public void setGetirResult(hataWS.ArrayOfHataBilgi getirResult) {
        this.getirResult = getirResult;
    }
}
