// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package hataWS;


public class GonderResponse {
    protected java.lang.String gonderResult;
    
    public GonderResponse() {
    }
    
    public GonderResponse(java.lang.String gonderResult) {
        this.gonderResult = gonderResult;
    }
    
    public java.lang.String getGonderResult() {
        return gonderResult;
    }
    
    public void setGonderResult(java.lang.String gonderResult) {
        this.gonderResult = gonderResult;
    }
}
