// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package hataWS;


public class Gonder {
    protected java.lang.String projeIsmi;
    protected long sonSoruId;
    protected int cevap;
    protected java.lang.String hataAciklama;
    protected long yollayanId;
    
    public Gonder() {
    }
    
    public Gonder(java.lang.String projeIsmi, long sonSoruId, int cevap, java.lang.String hataAciklama, long yollayanId) {
        this.projeIsmi = projeIsmi;
        this.sonSoruId = sonSoruId;
        this.cevap = cevap;
        this.hataAciklama = hataAciklama;
        this.yollayanId = yollayanId;
    }
    
    public java.lang.String getProjeIsmi() {
        return projeIsmi;
    }
    
    public void setProjeIsmi(java.lang.String projeIsmi) {
        this.projeIsmi = projeIsmi;
    }
    
    public long getSonSoruId() {
        return sonSoruId;
    }
    
    public void setSonSoruId(long sonSoruId) {
        this.sonSoruId = sonSoruId;
    }
    
    public int getCevap() {
        return cevap;
    }
    
    public void setCevap(int cevap) {
        this.cevap = cevap;
    }
    
    public java.lang.String getHataAciklama() {
        return hataAciklama;
    }
    
    public void setHataAciklama(java.lang.String hataAciklama) {
        this.hataAciklama = hataAciklama;
    }
    
    public long getYollayanId() {
        return yollayanId;
    }
    
    public void setYollayanId(long yollayanId) {
        this.yollayanId = yollayanId;
    }
}
