// This class was generated by 172 StubGenerator.
// Contents subject to change without notice.
// @generated

package hataWS;

public interface HataWSSoap extends java.rmi.Remote {
	public hataWS.ArrayOfHataBilgi getir(java.lang.String projeIsmi) throws java.rmi.RemoteException;

	public hataWS.SoruBilgi ilkSoru(java.lang.String projeIsmi) throws java.rmi.RemoteException;

	public hataWS.SoruBilgi sonraki(long id) throws java.rmi.RemoteException;

	public java.lang.String gonder(java.lang.String projeIsmi, long sonSoruId, int cevap, java.lang.String hataAciklama, long yollayanId) throws java.rmi.RemoteException;

}
