// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package hataWS;


public class HataBilgi {
    protected java.lang.String projeIsmi;
    protected java.lang.String aciklama;
    protected java.lang.String zaman;
    
    public HataBilgi() {
    }
    
    public HataBilgi(java.lang.String projeIsmi, java.lang.String aciklama, java.lang.String zaman) {
        this.projeIsmi = projeIsmi;
        this.aciklama = aciklama;
        this.zaman = zaman;
    }
    
    public java.lang.String getProjeIsmi() {
        return projeIsmi;
    }
    
    public void setProjeIsmi(java.lang.String projeIsmi) {
        this.projeIsmi = projeIsmi;
    }
    
    public java.lang.String getAciklama() {
        return aciklama;
    }
    
    public void setAciklama(java.lang.String aciklama) {
        this.aciklama = aciklama;
    }
    
    public java.lang.String getZaman() {
        return zaman;
    }
    
    public void setZaman(java.lang.String zaman) {
        this.zaman = zaman;
    }
}
