// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package hataWS;


public class IlkSoruResponse {
    protected hataWS.SoruBilgi ilkSoruResult;
    
    public IlkSoruResponse() {
    }
    
    public IlkSoruResponse(hataWS.SoruBilgi ilkSoruResult) {
        this.ilkSoruResult = ilkSoruResult;
    }
    
    public hataWS.SoruBilgi getIlkSoruResult() {
        return ilkSoruResult;
    }
    
    public void setIlkSoruResult(hataWS.SoruBilgi ilkSoruResult) {
        this.ilkSoruResult = ilkSoruResult;
    }
}
