// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package hataWS;


public class IlkSoru {
    protected java.lang.String projeIsmi;
    
    public IlkSoru() {
    }
    
    public IlkSoru(java.lang.String projeIsmi) {
        this.projeIsmi = projeIsmi;
    }
    
    public java.lang.String getProjeIsmi() {
        return projeIsmi;
    }
    
    public void setProjeIsmi(java.lang.String projeIsmi) {
        this.projeIsmi = projeIsmi;
    }
}
