// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package hataWS;


public class SonrakiResponse {
    protected hataWS.SoruBilgi sonrakiResult;
    
    public SonrakiResponse() {
    }
    
    public SonrakiResponse(hataWS.SoruBilgi sonrakiResult) {
        this.sonrakiResult = sonrakiResult;
    }
    
    public hataWS.SoruBilgi getSonrakiResult() {
        return sonrakiResult;
    }
    
    public void setSonrakiResult(hataWS.SoruBilgi sonrakiResult) {
        this.sonrakiResult = sonrakiResult;
    }
}
