// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JSR-172 Reference Implementation wscompile 1.0, using: JAX-RPC Standard Implementation (1.1, build R59)

package hataWS;


public class SoruBilgi {
    protected long id;
    protected java.lang.String soru;
    protected java.lang.String kNot;
    protected long evetId;
    protected long hayirId;
    
    public SoruBilgi() {
    }
    
    public SoruBilgi(long id, java.lang.String soru, java.lang.String kNot, long evetId, long hayirId) {
        this.id = id;
        this.soru = soru;
        this.kNot = kNot;
        this.evetId = evetId;
        this.hayirId = hayirId;
    }
    
    public long getId() {
        return id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    public java.lang.String getSoru() {
        return soru;
    }
    
    public void setSoru(java.lang.String soru) {
        this.soru = soru;
    }
    
    public java.lang.String getKNot() {
        return kNot;
    }
    
    public void setKNot(java.lang.String kNot) {
        this.kNot = kNot;
    }
    
    public long getEvetId() {
        return evetId;
    }
    
    public void setEvetId(long evetId) {
        this.evetId = evetId;
    }
    
    public long getHayirId() {
        return hayirId;
    }
    
    public void setHayirId(long hayirId) {
        this.hayirId = hayirId;
    }
}
